export const PRODUCTS = {
  'rocking-horse': {
    id: 'rocking-horse',
    name: 'Rattan Rocking Horse',
    category: 'Rattan Furniture',
    badge: "Children's Series",
    image: '/assets/rattan-horse-rocking.webp',
    shortDesc: "A timeless children's toy handcrafted from natural rattan manau.",
    desc: 'A timeless children\'s toy handcrafted from natural rattan manau with non-toxic water-based clear coat finish. Each piece is meticulously shaped and woven by skilled artisans to ensure both safety and beauty. An eco-friendly choice for nursery & kids\' room décor that will last for generations.',
    specs: [
      { key: 'Material', val: 'Natural Rattan Manau (Frame) & Rattan Core (Weaving)' },
      { key: 'Dimensions', val: '85 × 40 × 60 cm (L × W × H)' },
      { key: 'Finish', val: 'Water-based Clear Coat (Non-toxic / Lead-free)' },
      { key: 'Weight', val: '± 3.5 kg (unpackaged)' },
      { key: 'Age Range', val: '2–6 years old (max load 50 kg)' },
      { key: 'Surface', val: 'Smooth sanded, splinter-free' },
      { key: 'Color', val: 'Natural rattan tone with optional stain' },
      { key: 'Market', val: 'Eco-friendly Nursery & Kids\' Room Décor' },
      { key: 'Packaging', val: 'Bubble wrap + export carton box' },
      { key: 'MOQ', val: '5 units per order' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20the%20Rattan%20Rocking%20Horse.',
  },
  'rocking-chair': {
    id: 'rocking-chair',
    name: 'Ergonomic Rattan Rocking Chair',
    category: 'Rattan Furniture',
    badge: 'EU Certified',
    image: '/assets/photo-furniture02.webp',
    shortDesc: 'A premium adult rocking chair with contoured backrest for lumbar support.',
    desc: 'A premium adult rocking chair crafted from high-grade rattan poles with skin-on rattan accents. The contoured backrest is ergonomically shaped to provide lumbar support, while the reinforced base runners ensure long-term stability and smooth rocking motion on hard floors.',
    specs: [
      { key: 'Material', val: 'High-grade Rattan Poles with Skin-on Rattan accents' },
      { key: 'Dimensions', val: '110 × 62 × 95 cm (L × W × H)' },
      { key: 'Seat Height', val: '45 cm from floor' },
      { key: 'Max Load', val: '120 kg (residential use)' },
      { key: 'Features', val: 'Contoured ergonomic backrest, reinforced base runners' },
      { key: 'Finish', val: 'Natural lacquer or custom stain (upon request)' },
      { key: 'Joinery', val: 'Rattan lashing + metal bolt reinforcement at stress points' },
      { key: 'Compliance', val: 'EU strength & stability standards (residential)' },
      { key: 'Packaging', val: 'Assembled; padded moving blanket + export carton' },
      { key: 'MOQ', val: '3 units per order' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20the%20Ergonomic%20Rattan%20Rocking%20Chair.',
  },
  'room-divider': {
    id: 'room-divider',
    name: 'Rattan Hand Woven Room Divider',
    category: 'Rattan Furniture',
    badge: 'Interior Design',
    image: '/assets/hand-woven-room-devider.webp',
    shortDesc: 'A 3-panel folding screen with traditional inlaid rattan weaving.',
    desc: 'A 3-panel folding screen with traditional inlaid rattan weaving on a solid rattan frame. Heavy-duty hinges allow bi-directional folding, making it easy to configure as a straight partition or a free-standing zig-zag screen. Perfect for Boho-chic, Coastal, and Tropical interior themes.',
    specs: [
      { key: 'Material', val: 'Natural Rattan Frame with Traditional Inlaid Weaving' },
      { key: 'Dimensions', val: '150 × 3 × 180 cm (fully open); 50 cm per panel' },
      { key: 'Panel Count', val: '3 panels' },
      { key: 'Frame', val: 'Solid rattan poles, 22–25 mm diameter' },
      { key: 'Weaving', val: 'Hand-woven rattan core — traditional hexagonal pattern' },
      { key: 'Hardware', val: 'Heavy-duty brass or stainless steel bi-directional hinges' },
      { key: 'Finish', val: 'Natural or antique walnut stain (upon request)' },
      { key: 'Usage', val: 'Space partitioning, Boho-chic & Coastal interiors' },
      { key: 'Packaging', val: 'Folded; shrink-wrapped + padded corners + export carton' },
      { key: 'MOQ', val: '2 units per order' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20the%20Rattan%20Hand%20Woven%20Room%20Divider.',
  },
  'catappa-leaves': {
    id: 'catappa-leaves',
    name: 'Dried Catappa Leaves',
    category: 'Botanical Products',
    badge: 'Premium Grade A',
    image: '/assets/photo-catapang-leaf.webp',
    shortDesc: 'Premium Indian Almond Leaves for aquatic health, naturally sun-dried.',
    desc: 'Premium Indian Almond Leaves (Terminalia catappa) — hand-picked at peak maturity, carefully cleaned, and naturally sun-dried. The natural tannins released buffer pH, provide anti-bacterial properties, and reduce stress for betta fish, shrimp, and other sensitive aquatic life. No chemical treatment of any kind.',
    specs: [
      { key: 'Botanical Name', val: 'Terminalia catappa' },
      { key: 'Common Name', val: 'Indian Almond Leaf / Ketapang' },
      { key: 'Grade', val: 'Premium A — Hand-picked, cleaned, sun-dried' },
      { key: 'Sizes', val: 'Small 10–15 cm · Medium 16–25 cm · Large >25 cm' },
      { key: 'Color', val: 'Dark brown to mahogany, uniform tone' },
      { key: 'Moisture', val: '< 12% (mold prevention in transit)' },
      { key: 'Treatment', val: 'No chemicals, pesticides, or artificial drying' },
      { key: 'Packaging', val: 'Vacuum-sealed packs: 10, 50, or 100 pcs; bulk sacks on request' },
      { key: 'Compliance', val: 'Phytosanitary Certificate included' },
      { key: 'Shelf Life', val: '24 months in cool, dry storage' },
      { key: 'MOQ', val: '500 pcs per order' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Dried%20Catappa%20Leaves.',
  },
  'banana-leaves': {
    id: 'banana-leaves',
    name: 'Fresh Banana Leaves',
    category: 'Botanical Products',
    badge: 'Culinary Grade',
    image: '/assets/photo-banana-leaf04.webp',
    shortDesc: 'Culinary Grade banana leaves, organic and completely pesticide-free.',
    desc: 'Culinary Grade banana leaves carefully harvested at peak suppleness from organic plantations in Riau, Indonesia. Naturally aromatic, durable under heat, and completely free of pesticides — the perfect eco-friendly wrapper, plate liner, and steaming layer for authentic tropical and Asian cuisine worldwide.',
    specs: [
      { key: 'Botanical Name', val: 'Musa paradisiaca' },
      { key: 'Type', val: 'Whole leaf (midrib removed or intact on request)' },
      { key: 'Width', val: '30–40 cm' },
      { key: 'Length', val: '60–100 cm (custom cut available)' },
      { key: 'Color', val: 'Uniform vibrant green — no yellowing or dark spots' },
      { key: 'Treatment', val: 'Cleaned, sanitized, organic-grade (pesticide-free)' },
      { key: 'Harvest', val: 'Cut-to-order; within 24 hours of shipment' },
      { key: 'Packaging', val: 'PP bags, refrigerated styrofoam boxes 5–8°C (air freight)' },
      { key: 'Shelf Life', val: '10–14 days refrigerated; 2–3 days at room temp' },
      { key: 'Compliance', val: 'Phytosanitary Certificate + HACCP handling protocol' },
      { key: 'MOQ', val: '50 kg per shipment' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Fresh%20Banana%20Leaves.',
  },
  'kapulaga': {
    id: 'kapulaga',
    name: 'Kapulaga (Cardamom)',
    category: 'Spices',
    badge: 'Premium Grade',
    image: '/assets/kapulaga-copy.webp',
    shortDesc: 'Premium Indonesian Cardamom with rich aroma.',
    desc: 'Premium quality Indonesian Cardamom (Kapulaga) carefully dried to preserve its intense aromatic profile and natural essential oils. Essential for culinary applications and traditional medicine.',
    specs: [
      { key: 'Origin', val: 'Indonesia' },
      { key: 'Quality', val: 'Premium Export Grade' },
      { key: 'Packaging', val: 'Bulk sacks or vacuum sealed' },
      { key: 'Moisture', val: '< 14%' },
      { key: 'MOQ', val: '100 kg' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Kapulaga%20(Cardamom).',
  },
  'cloves': {
    id: 'cloves',
    name: 'Cloves (Cengkeh)',
    category: 'Spices',
    badge: 'Export Grade',
    image: '/assets/cloves2.webp',
    shortDesc: 'Hand-picked dried cloves with high oil content.',
    desc: 'Carefully hand-picked and naturally dried cloves (Cengkeh) from the best plantations in Indonesia. Known for their high eugenol oil content, strong aroma, and perfect reddish-brown color.',
    specs: [
      { key: 'Origin', val: 'Indonesia' },
      { key: 'Quality', val: 'Lal Pari / AB6 Grade' },
      { key: 'Packaging', val: 'PP Bags or Carton boxes' },
      { key: 'Foreign Matter', val: '< 1%' },
      { key: 'MOQ', val: '100 kg' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Cloves%20(Cengkeh).',
  },
  'ginger': {
    id: 'ginger',
    name: 'Dried Ginger',
    category: 'Spices',
    badge: 'Organic',
    image: '/assets/dried-ginger-copy.webp',
    shortDesc: 'Sliced and naturally dried ginger root.',
    desc: 'High-quality sliced and naturally sun-dried ginger root. Processed hygienically to ensure long shelf life while preserving its pungent flavor and medicinal properties. Perfect for tea, extraction, and culinary uses.',
    specs: [
      { key: 'Type', val: 'White/Red Ginger (Dried Sliced)' },
      { key: 'Moisture', val: '< 12%' },
      { key: 'Packaging', val: 'Mesh bags or Cartons' },
      { key: 'Treatment', val: 'Unbleached, naturally dried' },
      { key: 'MOQ', val: '100 kg' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Dried%20Ginger.',
  },
  'red-ginger': {
    id: 'red-ginger',
    name: 'Red Ginger (Jahe Merah)',
    category: 'Spices',
    badge: 'Premium Grade',
    image: '/assets/red-ginger-copy.webp',
    shortDesc: 'Freshly harvested robust red ginger.',
    desc: 'Premium red ginger known for its intense heat and high essential oil content. Widely used in traditional herbal medicine and premium spice blends.',
    specs: [
      { key: 'Origin', val: 'Indonesia' },
      { key: 'Type', val: 'Fresh or Dried Whole' },
      { key: 'Packaging', val: 'Mesh bags' },
      { key: 'MOQ', val: '100 kg' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Red%20Ginger.',
  },
  'ginger-powder': {
    id: 'ginger-powder',
    name: 'Ginger Powder',
    category: 'Spices',
    badge: 'Culinary Grade',
    image: '/assets/ginger-powder.webp',
    shortDesc: 'Finely ground pure ginger powder.',
    desc: '100% pure finely ground ginger powder made from select mature ginger roots. Perfect for baking, beverages, and industrial food processing.',
    specs: [
      { key: 'Origin', val: 'Indonesia' },
      { key: 'Mesh Size', val: '80-100 Mesh' },
      { key: 'Moisture', val: '< 10%' },
      { key: 'Packaging', val: 'Foil bags in cartons' },
      { key: 'MOQ', val: '50 kg' },
    ],
    waText: 'Hello%2C%20I%20am%20interested%20in%20Ginger%20Powder.',
  },
};

export const WA_NUMBER = '6287759282334';

export const GALLERY_IMAGES = [
  '/assets/photo-product-rotan01.webp',
  '/assets/photo-furniture02.webp',
  '/assets/photo-catapang-leaf.webp',
  '/assets/photo-banana-leaf.webp',
  '/assets/photo-product-rotan02.webp',
  '/assets/hand-woven-room-devider.webp',
];
